name: autofix.ci
run-name: 'autofix.ci "${{ github.event.pull_request.title || github.event.head_commit.message || github.event_name }}" by @${{ github.actor }}'
on:
  push: { branches: ["master"], paths-ignore: [".github/**"] }
  pull_request: { branches: ["**"], paths-ignore: [".github/**"] }
  workflow_call:
  workflow_dispatch:
permissions: { contents: read }
jobs:
  autofix:
    name: Format and autofix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: kjanat/install-dprint@v1
      - run: dprint fmt --allow-no-files --diff --excludes ".github"
      - uses: autofix-ci/action@v1
